# Generated by Django 4.1 on 2022-11-19 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('load_planer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery_plan',
            name='id',
        ),
        migrations.AlterField(
            model_name='delivery_plan',
            name='delivery_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exec_date', models.DateField()),
                ('delivery_time', models.TimeField()),
                ('f_pallets', models.PositiveSmallIntegerField()),
                ('c_pallets', models.PositiveSmallIntegerField()),
                ('d_pallets', models.PositiveSmallIntegerField()),
                ('delivery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='load_planer.delivery_plan')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='load_planer.destination')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='load_planer.driver')),
            ],
        ),
    ]
