# Generated by Django 4.1 on 2022-12-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_planer', '0002_destination_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='zipcode',
            field=models.CharField(default='0000', max_length=7),
        ),
    ]
