# Generated by Django 4.1 on 2022-11-19 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('load_planer', '0002_remove_delivery_plan_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tour',
        ),
    ]
