# Generated by Django 4.1 on 2022-11-20 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('load_planer', '0004_tour'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tour',
        ),
    ]
